# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-06-09 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksystem', '0003_like_is_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='food',
        ),
        migrations.AddField(
            model_name='store',
            name='like',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='booksystem.Like'),
            preserve_default=False,
        ),
    ]
