# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-06-10 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksystem', '0005_auto_20190609_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='is_favourite',
        ),
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
